# Generated by Django 4.1.9 on 2023-07-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CharApp",
            fields=[
                ("app_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "char_name",
                    models.CharField(max_length=80, verbose_name="Character Name"),
                ),
                ("date_applied", models.DateTimeField(verbose_name="Date Applied")),
                ("background", models.TextField(verbose_name="Background")),
                (
                    "account_id",
                    models.IntegerField(default=1, verbose_name="Account ID"),
                ),
                ("submitted", models.BooleanField(default=False)),
            ],
        ),
    ]
